# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6374fd675c492a7b89ccca5e2adb48b3f9ee09118de9be68f39f4c9e964b093d0105fa9280443af9ab7589e64357a18c6b94cd5f9e15266aa8cbd5f8a1065bf

test:
  secret_key_base: 2947074d8a27b20e4e7e4ff172645943359d892abc07f0be436e0ea23bf0471119f30e31fa377cdce1fcd51eca0fa47d0f8f285745e63aee2824b21d623d211e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
